server:
  port: 9090
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    # 最大等待队列，默认：100
    accept-count: 1000
    threads:
      # 最大线程，默认：200
      max: 1000
      # 初始线程，默认：25
      min-spare: 30

spring:
  application:
    # 项目名，小写，"-"连接
    name: generator
  messages:
    basename: i18n/messages
  aop:
    proxy-target-class: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization.write-dates-as-timestamps: false
